version: '3'

services:

  spring-boot:
    image: docker-spring-mysql2

    networks:
      - mysql-network

    ports:
      - "8080:8080"

    depends_on:
      - mysqldb1

  mysqldb1:
    image: mysql:8

    networks:
      - mysql-network

    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb  

networks:
  mysql-network:
